### ISSUE TITLE
[Firefox 68-72] Hide "Visit/Search" items does not work [semi workaround // fixed for megabar in Fx73+]

### ISSUE THREAD

**Issue by Hobbix** [Aris-t2/CustomCSSforFx#215]
Latest version "ac_popup_searchwith_and_visit_items_hidden.css" does not work. 
"Visit" line is not hiding.
![visit](https://user-images.githubusercontent.com/8199105/61102886-7e175580-a478-11e9-8919-f268697ec75a.png)

I used:
ac_popup_classic_with_two_lines_fx68.css
ac_popup_classic_with_two_lines_fx68_star_at_the_end.css
ac_popup_result_separator.css

**Comment by stampis** [comment]
Had to same issue; added this to the top of "ac_popup_searchwith_and_visit_items_hidden.css",
Did not check thru exactly what has changed, maybe "-moz-any" is redundant now?

`/* Remove " - Visit" or " - Search with" bar in the drop-down */
  #PopupAutoCompleteRichResult richlistitem:first-of-type[type*="heuristic"],
  #PopupAutoCompleteRichResult richlistitem:first-of-type[actiontype="searchengine"],
  #PopupAutoCompleteRichResult richlistitem:first-of-type[actiontype="visiturl"],
  #PopupAutoCompleteRichResult richlistitem:first-of-type[actiontype="keyword"],
  panel#urlbar-results #urlbarView-row-0 {
    display:none !important;
  }
/* Hide line for searching sld.tld below "Visit" Line */
  #PopupAutoCompleteRichResult richlistitem:first-of-type[actiontype="visiturl"] +
  richlistitem[actiontype="searchengine"] {
    display:none !important;
  }
  #PopupAutoCompleteRichResult .autocomplete-richlistbox,
  #urlbarView-results {
    padding-top: 0 !important;
    padding-bottom: 0 !important;
  }`

**Comment by Aris-t2** [comment]
@Hobbix  @stampis 
Atm the first result or maybe other too does not offer a "type" tag. Without it there is no way to hide the item properly.

This code will always hide the first result not just search/heuristic stuff.
```css
panel#urlbar-results #urlbarView-row-0 {
 display: none !important;
}
```

**Comment by motfis** [comment]
<img width="376" alt="Capture" src="https://user-images.githubusercontent.com/8572695/61336200-c34cd600-a830-11e9-99e4-4cc61a1bc163.PNG">

Why in my case the 2 lines search does not work properly..? The text overlap one to each other...

**Comment by Aris-t2** [comment]
Are you using the latest files and this option: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L717

Have you disabled https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L698 ?

**Comment by motfis** [comment]
> Have you disabled https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L698 ?

Ah yes, this fix the problem... I think I miss to disabled it when I updated the package.
Thanks!

**Comment by VengefulAncient** [comment]
> Are you using the latest files and this option: https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L717
L715 because I don't want the star, but otherwise yes.
> Have you disabled https://github.com/Aris-t2/CustomCSSforFx/blob/master/classic/userChrome.css#L698 ?
Yes.

Yet the issue persists.

**Comment by Aris-t2** [comment]
Hiding those items works again in Fx73+ when using megabar (enabled by default).

**Comment by Aris-t2** [comment]
I think this can be closed now.
