### ISSUE TITLE
issue with latest firefox 142 and 143

### ISSUE THREAD

**Issue by p060477** [Aris-t2/CustomCSSforFx#777]
### Guidelines

- [x] I have read [how to report a new issue](https://github.com/Aris-t2/CustomCSSforFx/issues/4)
- [x] I have used the [latest release](https://github.com/Aris-t2/CustomCSSforFx/releases/latest)
- [x] I have set the `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config` to `true`

### Does the issue occur without any files inside /chrome/ folder?

Yes

### Does the issue occur with the most recent version of CustomCSSforFx (release/test/dev build)?

Yes, with the latest release

### Screenshots showing the issue

pls see this image:

![Image](https://github.com/user-attachments/assets/b0272da2-cefa-4e8d-811d-0549c04ac8e7)

as you can see the folder in bookmars tab are coloured as always in yellow
but their sub-folder has no clour...
see for ex the bookmars tab folder named:CH is yellowed colour
but its subfolders: CH2, crea spartito and CT have really no colour...
how to have also them in yellow colours as for their main folder named CH?
thxs in adv
cheers

### System information

- OS & OS version:  win 10 home 64
- DPI/HiDPI/scaling value, if not 100% (e.g. 125%, 150%...): 
- Firefox version: 143
- Firefox theme (e.g. default, build in light/dark, external theme + link): dark

**Comment by p060477** [comment]
to be clearer i want it back to this:

![Image](https://github.com/user-attachments/assets/0d1b8530-56ab-428a-a296-a0dc3253c44c)

that is the theme i've on my tor browser based on firefox 128esr....the chrome folder is the same as my latest 
ff 143 that have this issue i'd like to solve:

ff 143 theme

![Image](https://github.com/user-attachments/assets/7aed342f-867b-42fb-963e-2d9dbf4ace93)

**Comment by MarkRH** [comment]
Yeah, looks like both the Bookmarks Menu and Bookmark Toolbar subfolders have reverted back to the monochrome icons. I was also using those yellowish looking folders.

<img width="396" height="301" alt="Image" src="https://github.com/user-attachments/assets/3eb4eac6-4713-4867-a9ea-130004cff3ba" />

Bookmark Menu:
<img width="259" height="375" alt="Image" src="https://github.com/user-attachments/assets/2fd56fd1-4378-4373-8473-4e00097c143d" />

**Comment by Nicholas-Steel** [comment]
I can confirm this issue with the System Theme (auto) 1.4.2 in Windows 10 22H2

Edit: GlennPC's suggestion below goes in to the my_userChrome.css file

**Comment by glennpc** [comment]
Try this to get the yellow icons back:

.bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon){ content: url("./image/folder-item.png") !important; }

**Comment by Nicholas-Steel** [comment]
> Try this to get the yellow icons back:
> 
> .bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon){ content: url("./image/folder-item.png") !important; }

This did not work for me when added to my_userChrome.css in Firefox 143, Windows 10 22H2.

**Comment by glennpc** [comment]
@Nicholas-Steel do you have bookmark_icons_colorized.css enabled in the userChrome.css ?

**Comment by MarkRH** [comment]
> Try this to get the yellow icons back:
> 
> .bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon){ content: url("./image/folder-item.png") !important; }

That did not work for me.  It actually removed the icons completely. 

<img width="404" height="208" alt="Image" src="https://github.com/user-attachments/assets/73184226-2d05-40a4-9acc-ec9263939f19" />

and 

<img width="273" height="296" alt="Image" src="https://github.com/user-attachments/assets/a2390c91-9926-4688-b658-c0163cca7472" />

I do have bookmark_icons_colorized.css enabled. Hmmm.

**Comment by glennpc** [comment]
@MarkRH perhaps the folder-item.png file is missing?

**Comment by MarkRH** [comment]
> [@MarkRH](https://github.com/MarkRH) perhaps the folder-item.png file is missing?

Since my chrome folder is structured differently, forgot I needed to change the path to:
```
/* Set Bookmark Folders back to yellow in FX143 */
.bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon) {
   content: url("./classic475/image/folder-item.png") !important;
} /**/
```

So now they show up.  But, it also affects the icons in the Bookmark Menu that I don't think were folder icons before, like Recent Tags and such.  Maybe I'm misremembering.

<img width="267" height="301" alt="Image" src="https://github.com/user-attachments/assets/2cd0012d-7211-4d31-a98a-76c5f61684c4" />

**Comment by Nicholas-Steel** [comment]
> [@Nicholas-Steel](https://github.com/Nicholas-Steel) do you have bookmark_icons_colorized.css enabled in the userChrome.css ?

Yeah. In my case it remains the wireframe icons in the menu (toolbar is correct yellow), not the yellow vanilla folder.

<img width="418" height="228" alt="Image" src="https://github.com/user-attachments/assets/2de09884-5d06-4000-9877-887c45506789" />

**Comment by glennpc** [comment]
> Since my chrome folder is structured differently, forgot I needed to change the path

Oh that's why. Perhaps when @Aris-t2 gets back on, he can help you further.

**Comment by p060477** [comment]
hi, i'm a little bit confused..but have you solved?
if yes could you pls write here in details what we have to do to rehave:

![Image](https://github.com/user-attachments/assets/92855884-25f0-4511-afc9-7f3f58681c6c)

maybe only Aris will be able to finally help us and solve
hope to see him here soon
thxs to all
cheers

**Comment by p060477** [comment]
now i'm in the same situation of MarkRH:

<img width="267" height="301" alt="Image" src="https://github.com/user-attachments/assets/46a5472b-0d47-455d-9936-69a726b06a6b" />

Bookmarks toolbar, Other Bookmarks, Most Visited ,Recent Tags ,Recently Bookmarked
all are really NOT folder created by me as new folders..
so they really do not have to have the yellow colour 
i mean this: image/folder-item.png...cause as i said they really are not folders created by me
so they shouldn't be in yellow.....
how to solve?

**Comment by p060477** [comment]
to be more clear at all see this image:

<img width="800" height="634" alt="Image" src="https://github.com/user-attachments/assets/552afa09-e985-4020-b4a2-af98064c53b6" />

looking at the left side of screen this is my situation now...
but the right should be the right side 
tried this my_userChrome.css file:
`.bookmark-item[container]>:is(.menu-icon,.toolbarbutton-icon){ content:url("./image/folder-item.png")!important;
}
.bookmarksToolbar[container]>:is(.menu-icon,.toolbarbutton-icon){ content:url("./image/bookmarksToolbar.png")!important;
}
.unsortedBookmarks[container]>:is(.menu-icon,.toolbarbutton-icon) { content:url("./image/unsortedBookmarks.png")!important;
}
 `

but really do not solve at all...my situation remains the one showed on the left side of the image i post above

where is Aris...??

**Comment by p060477** [comment]
this is the right situation pre ff 143 infact this image is taken from my tor which is based on ff 128esr:

![Image](https://github.com/user-attachments/assets/c6b24205-d2bd-4a99-8a4d-7e02d418fbe3)

i take its chrome folder and put it in my ff 143 but really do not solve....
so the matter is a BUG between  Aris-t2 CustomCSSforFx  and the new ff 143
so really hope Aris to finally reappear here to solve
thxs in adv
cheers

**Comment by wodixxxx** [comment]
Since Firefox 143 the folder icons in bookmark popups stopped reacting to list-style-image.
The fix is to target .menu-icon directly and set your own icon:

`menupopup[placespopup="true"] .bookmark-item[container] > .menu-icon {
  content: url("image/folder-item.png") !important;
}
`

<img width="111" height="75" alt="Image" src="https://github.com/user-attachments/assets/4c5e9d97-3c9c-4bd9-a7df-1f37420ffb17" />

For me it works.

**Comment by p060477** [comment]
@wodixxxx  : thxs but i really do not want them as in yr image.....(infact you use url("image/folder-item.png")
i'd like them as per my latest pic as i still have in my tor browser:

![Image](https://github.com/user-attachments/assets/8050feb3-4fb6-43bd-bda3-c3a30700d676)
what about: bookmarks toolbar,other bookmarks,most recents,most visited and recent tags
with yr code they are all in yellow colour as per folder-item.png
but they really aren't folders created by me so the yellow colour is wrong
they ,for example, should be as:

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/ff971f05-2514-4cac-b823-39dbed42bc1c" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/bd3aa991-b126-4e9c-9eca-b1ac05454ff1" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/788bef93-81e5-4817-baf5-5f0bfc40f3eb" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/285eda28-b39e-492e-bdca-41be09b69b7d" />

see the picture of my tor situation:

![Image](https://github.com/user-attachments/assets/448066aa-3a48-4072-9ed6-c582d50eb04d)

so pls write the exact code i've to use
thxs really so much in adv
cheers

**Comment by Nicholas-Steel** [comment]
> > Try this to get the yellow icons back:
> > .bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon){ content: url("./image/folder-item.png") !important; }
> 
> This did not work for me when added to my_userChrome.css in Firefox 143, Windows 10 22H2.

I figured out my issue, it turns out I had an unescaped comment in my my_userChrome.css file. The icons are back to being yellow once I addressed this mistake while adding your commands to the file.

**Comment by p060477** [comment]
this issue is still there unsolved:
what about: bookmarks toolbar,other bookmarks,most recents,most visited and recent tags
with yr code they are all in yellow colour as per folder-item.png
but they really aren't folders created by me so the yellow colour is wrong
they ,for example, should be as:

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/ff971f05-2514-4cac-b823-39dbed42bc1c" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/bd3aa991-b126-4e9c-9eca-b1ac05454ff1" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/788bef93-81e5-4817-baf5-5f0bfc40f3eb" />

<img width="16" height="16" alt="Image" src="https://github.com/user-attachments/assets/285eda28-b39e-492e-bdca-41be09b69b7d" />

see the picture of my tor situation:

![Image](https://github.com/user-attachments/assets/448066aa-3a48-4072-9ed6-c582d50eb04d)

so pls write the exact code i've to use
thxs really so much in adv
cheers

**Comment by Nicholas-Steel** [comment]
No need to repeat yourself, if someone has the answer to your problem they'll post the solution.

**Comment by nicolaasjan** [comment]
[This answer](https://github.com/Aris-t2/CustomCSSforFx/discussions/722#discussioncomment-14442565) from @anzuno in the Discussions thread fixed the issue for me.

In `./chrome/css/generalui/bookmark_icons_colorized.css`, overwrite line 116 and beyond with:

```css
/*** Fx143 ***/
#bookmarksToolbarFolderMenu > :is(.menu-icon,.menu-iconic-icon),
#BMB_bookmarksToolbar > :is(.menu-icon,.menu-iconic-icon),
#editBMPanel_toolbarFolderItem > :is(.menu-icon, .toolbarbutton-icon) {
content: url("./../../image/bookmarksToolbar.png") !important;
}

#menu_unsortedBookmarks > :is(.menu-icon,.menu-iconic-icon),
#BMB_unsortedBookmarks > :is(.menu-icon,.menu-iconic-icon),
#editBMPanel_unfiledRootItem > :is(.menu-icon,.menu-iconic-icon) {
content: url("./../../image/unsortedBookmarks.png") !important;
}

#editBMPanel_folderMenuList[selectedGuid="unfiled_____"] {
list-style-image: url("./../../image/unsortedBookmarks.png") !important;
}

#editBMPanel_folderMenuList[selectedGuid="toolbar_____"] {
list-style-image: url("./../../image/bookmarksToolbar.png") !important;
}

#editBMPanel_folderMenuList[selectedGuid="menu________"] {
list-style-image: url("./../../image/bookmarksMenu.png") !important;
}

.bookmark-item[container] > :is(.menu-icon, .toolbarbutton-icon),
.folder-icon > :is(.menu-icon, .toolbarbutton-icon) {
content: url("./../../image/folder-item.png") !important;
}

#editBMPanel_bmRootItem > :is(.menu-icon, .toolbarbutton-icon) {
content: url("./../../image/bookmarksMenu.png") !important;
}

/* "Other Bookmarks" folder in the Bookmarks Toolbar */
#OtherBookmarks > :is(.menu-icon, .toolbarbutton-icon) {
content: url("./../../image/unsortedBookmarks.png") !important;
}
```

**Comment by p060477** [comment]
in my case  what about: bookmarks toolbar,other bookmarks,most recents,most visited and recent tags
solved only 2 bugs of the 5...the three lefst remains in yellow
see:

![Image](https://github.com/user-attachments/assets/3dc44a07-488b-4e13-a534-da765abb2a75)

to sum up solved the first 2:bookmarks toolbar,other bookmarks
but not the 3 left:
most recents,most visited and recent tags
that are still yellowed colour as folder created by me
so the trick partially fix: 2/5
